import { Credits } from "./schemas/credits";
import { Movie } from "./schemas/movie";

// Data from https://www.themoviedb.org/

const dummyResults: Movie[] = [
  {
    adult: false,
    backdrop_path: "/iUAFLqAj7p1v8zkOReyd7tjSLDg.jpg",
    genre_ids: [18, 35],
    id: 341744,
    original_language: "es",
    original_title: "Truman",
    overview:
      "Tomás, who lives in Canada, travels to Madrid, Spain, to visit his old friend Julián. Both of them, accompanied by Truman, Julián's faithful dog, will share many surprising and emotional little moments, triggered by the hard situation Julián is going through, for just a few days.",
    popularity: 9.364,
    poster_path: "/p4MFl06ePJGKMIF7zFCJhex95Vi.jpg",
    release_date: "2015-09-24",
    title: "Truman",
    video: false,
    vote_average: 7.006,
    vote_count: 346,
  },
  {
    adult: false,
    backdrop_path: "/xZRuns3IlPxnzpHhbscAOLyiwNr.jpg",
    genre_ids: [18, 10770],
    id: 16901,
    original_language: "en",
    original_title: "Truman",
    overview:
      "Biographical account of America's President for the latter part of WWII. Shows Truman's rise from small-town nobody to leader of the USA, his decision to use the Atomic Bomb against Japan, and subsequent election as the US' post-war President.",
    popularity: 2.905,
    poster_path: "/4SW6da4XjxLGlRVS079O1ORpjqk.jpg",
    release_date: "1995-09-09",
    title: "Truman",
    video: false,
    vote_average: 7.6,
    vote_count: 15,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [99],
    id: 365256,
    original_language: "en",
    original_title: "Truman",
    overview:
      "He was a farmer, a businessman, an unknown politician who suddenly found himself president. Of all the men who had held the highest office, Harry Truman was the least prepared, but would prove to be a surprise.",
    popularity: 0.6,
    poster_path: null,
    release_date: "1997-10-05",
    title: "Truman",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/aCHn2TXYJfzPXQKA6r9mKPbMlUB.jpg",
    genre_ids: [35, 18],
    id: 37165,
    original_language: "en",
    original_title: "The Truman Show",
    overview:
      "Truman Burbank is the star of The Truman Show, a 24-hour-a-day reality TV show that broadcasts every aspect of his life without his knowledge. His entire life has been an unending soap opera for consumption by the rest of the world. And everyone he knows, including his wife and his best friend, is really an actor, paid to be part of his life.",
    popularity: 71.661,
    poster_path: "/vuza0WqY239yBXOadKlGwJsZJFE.jpg",
    release_date: "1998-06-04",
    title: "The Truman Show",
    video: false,
    vote_average: 8.132,
    vote_count: 16690,
  },
  {
    adult: false,
    backdrop_path: "/pmsfi7seRvhj5FpR1T1USD08txG.jpg",
    genre_ids: [99],
    id: 730081,
    original_language: "en",
    original_title: "Truman & Tennessee: An Intimate Conversation",
    overview:
      "The parallel lives of writer Truman Capote (1924-84) and playwright Tennessee Williams (1911-83): two friends, two geniuses who, while creating sublime works, were haunted by the ghosts of the past, the shadow of constant doubt, the demon of addictions and the blinding, deceptive glare of success.",
    popularity: 2.632,
    poster_path: "/yBLui5HtiyAFWQqVXjqSdJeRLdv.jpg",
    release_date: "2021-06-18",
    title: "Truman & Tennessee: An Intimate Conversation",
    video: false,
    vote_average: 4,
    vote_count: 2,
  },
  {
    adult: false,
    backdrop_path: "/zYTNycZ3QPGFwlUbRrjyPkWvik4.jpg",
    genre_ids: [99],
    id: 298662,
    original_language: "en",
    original_title: "With Love from Truman",
    overview:
      "At his Long Island beach house, and on the occasion of the publication of his masterful nonfiction novel In Cold Blood, reporter Karen Dennison interviews celebrated writer Truman Capote, who displays his exuberant personality, makes witty jokes, shares his thoughts on writing, reflects on various aspects of the book and, in a sweet and endearing voice, reads and explains some of its highlights.",
    popularity: 0.812,
    poster_path: "/n60IVg19EaNNRwqvpGatOGlsWIY.jpg",
    release_date: "1966-01-01",
    title: "With Love from Truman",
    video: false,
    vote_average: 6.2,
    vote_count: 6,
  },
  {
    adult: false,
    backdrop_path: "/pUH4DkA9THIrCXhKp5UFLhjLDyh.jpg",
    genre_ids: [99],
    id: 742930,
    original_language: "en",
    original_title: "How's It Going to End - The Making of 'The Truman Show'",
    overview: "The making of 'The Truman Show'.",
    popularity: 0.676,
    poster_path: "/3u7lkckEG1KJK1yWnBL0FMVg9qg.jpg",
    release_date: "2005-08-19",
    title: "How's It Going to End - The Making of 'The Truman Show'",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [18, 10770],
    id: 263221,
    original_language: "en",
    original_title: "Harry S. Truman: Plain Speaking",
    overview: "A biography of President Harry S. Truman.",
    popularity: 0.654,
    poster_path: "/7EzzuZQEHqjOwMoV1T4J37VqPkg.jpg",
    release_date: "1976-10-06",
    title: "Harry S. Truman: Plain Speaking",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/32YCKPHxiMZcH2MOzSBZsF0EEk6.jpg",
    genre_ids: [10402],
    id: 1067909,
    original_language: "en",
    original_title: "Goose: 2021.11.17 - The Truman - Kansas City, MO",
    overview:
      "Set 1: Earthlings or Alien? > Indian River > Doctor My Eyes, SOS, All I Need > Bob Don > All I Need  Set 2: Arcadia > Crosseyed and Painless > Drive > Moby, 726, Into The Myst  Encore: Doobie Song",
    popularity: 0.6,
    poster_path: "/f4fbK3qI4UyFIZVXlXfkCrqtiYd.jpg",
    release_date: "2021-11-17",
    title: "Goose: 2021.11.17 - The Truman - Kansas City, MO",
    video: true,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/xLANFjyrdj0qUeQUkaFUDkXgrJ.jpg",
    genre_ids: [99, 10752, 36],
    id: 594957,
    original_language: "fr",
    original_title: "Staline-Truman, l'aube de la guerre froide",
    overview: "",
    popularity: 0.6,
    poster_path: "/nSgkcYxPTVucOXdsjfCjxTWytKn.jpg",
    release_date: "2019-04-04",
    title: "Staline-Truman, l'aube de la guerre froide",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [99],
    id: 670673,
    original_language: "de",
    original_title:
      "Truman Capote - Enfant terrible der amerikanischen Literatur",
    overview: "",
    popularity: 0.63,
    poster_path: "/1zS7gZUetZdojLEA3kwJOZThbQr.jpg",
    release_date: "2016-11-16",
    title: "Truman Capote - Enfant terrible der amerikanischen Literatur",
    video: false,
    vote_average: 9,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [99],
    id: 973055,
    original_language: "en",
    original_title: "Truman Capote: Answered Prayers",
    overview:
      "A short documentary looking at how the film Capote was developed, the motivations of those involved, and insights from Gerald Clarke, Capote's friend and biographer.",
    popularity: 0.6,
    poster_path: "/qNcdLvqoG3i37ceDyy3WjmEc7lR.jpg",
    release_date: "2006-03-21",
    title: "Truman Capote: Answered Prayers",
    video: false,
    vote_average: 4,
    vote_count: 2,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [18],
    id: 786749,
    original_language: "en",
    original_title: "Truman Syndrome",
    overview:
      "A person who believes they're being watched all day, every day, struggles with their mental health and their grip on reality.",
    popularity: 0.6,
    poster_path: "/f3lrhJr7M8pk1A0ljUzrnUgsjCP.jpg",
    release_date: "2021-01-21",
    title: "Truman Syndrome",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 810559,
    original_language: "en",
    original_title: "David Susskind Archive: Truman Capote Tells All",
    overview:
      "An extensive interview originally broadcast in Feb. 1979. Host David Susskind and Truman Capote discuss the icon's history, his writing, his social persona and impact. More than an interview, the wide-ranging conversation between longtime friends delves into topics you are unlikely to see elsewhere.",
    popularity: 0.6,
    poster_path: null,
    release_date: "",
    title: "David Susskind Archive: Truman Capote Tells All",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [10752, 18, 10770],
    id: 1156740,
    original_language: "en",
    original_title: "Collision Course: Truman vs. MacArthur",
    overview:
      "U.S. President Harry S Truman and his commander in the Korean War, General Douglas MacArthur, disagree on war strategy. Their conflict comes to a head when Truman relieves the insubordinate MacArthur from command.",
    popularity: 0.6,
    poster_path: null,
    release_date: "1976-01-04",
    title: "Collision Course: Truman vs. MacArthur",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/gQYsE1Zu89fbi3yUL4bubxoRjbh.jpg",
    genre_ids: [80, 18],
    id: 18900,
    original_language: "en",
    original_title: "In Cold Blood",
    overview:
      "After a botched robbery results in the brutal murder of a rural family, two drifters elude police, in the end coming to terms with their own mortality and the repercussions of their vile atrocity.",
    popularity: 12.319,
    poster_path: "/9VFk7hyx3Thk8kzChq750rLtrsR.jpg",
    release_date: "1967-12-15",
    title: "In Cold Blood",
    video: false,
    vote_average: 7.5,
    vote_count: 313,
  },
  {
    adult: false,
    backdrop_path: "/kA28hzGAais4Rlk0RG6PsQzTqU4.jpg",
    genre_ids: [18, 80],
    id: 9672,
    original_language: "en",
    original_title: "Infamous",
    overview:
      "While researching his book In Cold Blood, writer Truman Capote develops a close relationship with convicted murderers Dick Hickock and Perry Smith.",
    popularity: 11.293,
    poster_path: "/cIQUn20lUQpi70W0Z7ixezQJ7gj.jpg",
    release_date: "2006-09-11",
    title: "Infamous",
    video: false,
    vote_average: 6.478,
    vote_count: 179,
  },
  {
    adult: false,
    backdrop_path: "/gBn3af5QvQARNZEFlvYjFO268I7.jpg",
    genre_ids: [80, 18],
    id: 398,
    original_language: "en",
    original_title: "Capote",
    overview:
      'A biopic of writer Truman Capote and his assignment for The New Yorker to write the non-fiction book "In Cold Blood".',
    popularity: 12.676,
    poster_path: "/k7z0tDxzbDNev7F8l3Y56Pk5seR.jpg",
    release_date: "2005-09-30",
    title: "Capote",
    video: false,
    vote_average: 6.998,
    vote_count: 1287,
  },
  {
    adult: false,
    backdrop_path: "/r3eo0srAqazG1lFMuqPzJqdyGce.jpg",
    genre_ids: [99],
    id: 621769,
    original_language: "en",
    original_title: "The Capote Tapes",
    overview:
      "Newly discovered interviews with friends of Truman Capote made by Paris Review co-founder George Plimpton invigorate this fascinating documentary on the author (and socialite) behind Breakfast at Tiffany’s and In Cold Blood, while situating Capote in the 20th-century American literary canon.",
    popularity: 4.311,
    poster_path: "/iOxtoUHHxDF9ZEhTNqFUWjpWgDH.jpg",
    release_date: "2021-09-10",
    title: "The Capote Tapes",
    video: false,
    vote_average: 7.8,
    vote_count: 4,
  },
  {
    adult: false,
    backdrop_path: "/2Fa1IO7qcXX9KlnocFyhPNUxRwb.jpg",
    genre_ids: [18, 10751],
    id: 147135,
    original_language: "en",
    original_title: "One Christmas",
    overview:
      "Based on Truman Capote's bittersweet tale of a young boy's adventures with the father he's never known in New Orleans in the 1930s..",
    popularity: 1.484,
    poster_path: "/uTVZyFVVJ5WVjH1G08UxeKSv9tw.jpg",
    release_date: "1994-12-19",
    title: "One Christmas",
    video: false,
    vote_average: 5.5,
    vote_count: 8,
  },
] as Object as Movie[];

const dummyCredits: Credits = {
  id: 1149947,
  cast: [
    {
      adult: false,
      gender: 2,
      id: 1197805,
      known_for_department: "Acting",
      name: "J. Robert Oppenheimer",
      original_name: "J. Robert Oppenheimer",
      popularity: 2.937,
      profile_path: "/9FaAqdF4LiowhOpHUhBAsnNfArS.jpg",
      cast_id: 6,
      character: "Self (archive footage)",
      credit_id: "64b2e2d023d278014584a68e",
      order: 0,
    },
    {
      adult: false,
      gender: 1,
      id: 4164414,
      known_for_department: "Acting",
      name: "Ellen Bradbury Reid",
      original_name: "Ellen Bradbury Reid",
      popularity: 0.98,
      profile_path: null,
      cast_id: 95,
      character: "Self - Daughter of Los Alamos Scientist",
      credit_id: "64b2e900378062011c8b061f",
      order: 1,
    },
    {
      adult: false,
      gender: 2,
      id: 525,
      known_for_department: "Directing",
      name: "Christopher Nolan",
      original_name: "Christopher Nolan",
      popularity: 34.607,
      profile_path: "/xuAIuYSmsUzKlUMBFGVZaWsY3DZ.jpg",
      cast_id: 2,
      character: 'Self - Writer / Director, "Oppenheimer"',
      credit_id: "64aaeb9b6a344800ea8cbd95",
      order: 2,
    },
    {
      adult: false,
      gender: 2,
      id: 1197811,
      known_for_department: "Directing",
      name: "Jon Else",
      original_name: "Jon Else",
      popularity: 1.137,
      profile_path: "/yGhdZGBPGDy0rwNn7Lj9Epnilrd.jpg",
      cast_id: 91,
      character: 'Self - Filmmaker, "The Day After Trinity"',
      credit_id: "64b2e77fe0ca7f00e771ae54",
      order: 3,
    },
    {
      adult: false,
      gender: 2,
      id: 2334219,
      known_for_department: "Writing",
      name: "Kai Bird",
      original_name: "Kai Bird",
      popularity: 1.105,
      profile_path: null,
      cast_id: 92,
      character: 'Self - Co-Author, "American Prometheus"',
      credit_id: "64b2e79278570e011da8f768",
      order: 4,
    },
    {
      adult: false,
      gender: 2,
      id: 1218795,
      known_for_department: "Acting",
      name: "Bill Nye",
      original_name: "Bill Nye",
      popularity: 7.219,
      profile_path: "/HfEBnQuiCMPjcsONf9FCpnEyJL.jpg",
      cast_id: 3,
      character: "Self - Science Educator",
      credit_id: "64aaebbfd1a8930139d6a174",
      order: 5,
    },
    {
      adult: false,
      gender: 2,
      id: 1181378,
      known_for_department: "Acting",
      name: "Richard Rhodes",
      original_name: "Richard Rhodes",
      popularity: 0.98,
      profile_path: null,
      cast_id: 93,
      character: 'Self - Author, "The Making of the Atomic Bomb"',
      credit_id: "64b2e88078570e00e33ad66e",
      order: 6,
    },
    {
      adult: false,
      gender: 1,
      id: 4164413,
      known_for_department: "Acting",
      name: "Mareena Robinson Snowden",
      original_name: "Mareena Robinson Snowden",
      popularity: 1.38,
      profile_path: null,
      cast_id: 94,
      character: "Self - Nuclear Security Expert",
      credit_id: "64b2e8cc23d278014584a91c",
      order: 7,
    },
    {
      adult: false,
      gender: 2,
      id: 2471528,
      known_for_department: "Acting",
      name: "Alan B. Carr",
      original_name: "Alan B. Carr",
      popularity: 1.094,
      profile_path: null,
      cast_id: 97,
      character: "Self - Senior Historian, Los Alamos National Laboratory",
      credit_id: "64b2e9740cb33500e2bc3e1a",
      order: 8,
    },
    {
      adult: false,
      gender: 2,
      id: 4164417,
      known_for_department: "Acting",
      name: "Gregg Herken",
      original_name: "Gregg Herken",
      popularity: 0.6,
      profile_path: null,
      cast_id: 98,
      character: 'Self - Author, "Brotherhood of the Bomb"',
      credit_id: "64b2e9c80bb076014e4ea844",
      order: 9,
    },
    {
      adult: false,
      gender: 1,
      id: 4164418,
      known_for_department: "Acting",
      name: "Jennet Conant",
      original_name: "Jennet Conant",
      popularity: 0.6,
      profile_path: null,
      cast_id: 99,
      character: 'Self - Author, "109 East Palace"',
      credit_id: "64b2ea210bb07600ae3bbec3",
      order: 10,
    },
    {
      adult: false,
      gender: 2,
      id: 1365823,
      known_for_department: "Acting",
      name: "David Eisenbach",
      original_name: "David Eisenbach",
      popularity: 1.686,
      profile_path: null,
      cast_id: 100,
      character: "Self - History Professor, Columbia University",
      credit_id: "64b2ea5c0bb076012d57f9fc",
      order: 11,
    },
    {
      adult: false,
      gender: 2,
      id: 4164421,
      known_for_department: "Acting",
      name: "Alex Wellerstein",
      original_name: "Alex Wellerstein",
      popularity: 0.6,
      profile_path: null,
      cast_id: 101,
      character: "Self - Nuclear Historian",
      credit_id: "64b2eaaa37806200e2aaef12",
      order: 12,
    },
    {
      adult: false,
      gender: 2,
      id: 1778411,
      known_for_department: "Acting",
      name: "Martin J. Sherwin",
      original_name: "Martin J. Sherwin",
      popularity: 0.6,
      profile_path: null,
      cast_id: 102,
      character: 'Self - Co-Author, "American Prometheus" (voice)',
      credit_id: "64b2eb2bc8a2d400c622a301",
      order: 13,
    },
    {
      adult: false,
      gender: 2,
      id: 83299,
      known_for_department: "Acting",
      name: "Michio Kaku",
      original_name: "Michio Kaku",
      popularity: 4.68,
      profile_path: "/brVv7KevXyEraj4vhcNySAc8myb.jpg",
      cast_id: 103,
      character: "Self - Theoretical Physicist",
      credit_id: "64b2eb440bb07600eb28ce25",
      order: 14,
    },
    {
      adult: false,
      gender: 2,
      id: 1197810,
      known_for_department: "Acting",
      name: "Leslie Groves",
      original_name: "Leslie Groves",
      popularity: 1.104,
      profile_path: "/rdQkaIpxxlOOLKnu1ug1ACghET2.jpg",
      cast_id: 104,
      character: "Self - Director, Manhattan Project (voice) (archive footage)",
      credit_id: "64b2eb650cb33500adb447d9",
      order: 15,
    },
    {
      adult: false,
      gender: 2,
      id: 4164423,
      known_for_department: "Acting",
      name: "Charles Oppenheimer",
      original_name: "Charles Oppenheimer",
      popularity: 0.98,
      profile_path: null,
      cast_id: 105,
      character: "Self - Grandson",
      credit_id: "64b2eb7637806200c586e9f2",
      order: 16,
    },
    {
      adult: false,
      gender: 2,
      id: 4164427,
      known_for_department: "Acting",
      name: "Robert Christy",
      original_name: "Robert Christy",
      popularity: 0.6,
      profile_path: null,
      cast_id: 106,
      character: "Self - Theoretical Physicist (voice) (archive footage)",
      credit_id: "64b2ebdd0e4fc800e3351ef3",
      order: 17,
    },
    {
      adult: false,
      gender: 2,
      id: 4164432,
      known_for_department: "Acting",
      name: "Robert S. Norris",
      original_name: "Robert S. Norris",
      popularity: 0.6,
      profile_path: null,
      cast_id: 107,
      character: 'Self - Author, "Racing for the Bomb"',
      credit_id: "64b2ec4978570e00ad4b5db8",
      order: 18,
    },
    {
      adult: false,
      gender: 1,
      id: 4164389,
      known_for_department: "Acting",
      name: "Hideko Tamura",
      original_name: "Hideko Tamura",
      popularity: 0.6,
      profile_path: null,
      cast_id: 108,
      character: "Self - Hiroshima Survivor (Age 10)",
      credit_id: "64b2ece1c8a2d401001e7448",
      order: 19,
    },
    {
      adult: false,
      gender: 2,
      id: 4164440,
      known_for_department: "Acting",
      name: "Roy Glauber",
      original_name: "Roy Glauber",
      popularity: 0.6,
      profile_path: null,
      cast_id: 109,
      character:
        "Self - Scientist, Manhattan Project (voice) (archive footage)",
      credit_id: "64b2ed3ae0ca7f00ae756ca0",
      order: 20,
    },
    {
      adult: false,
      gender: 2,
      id: 1944259,
      known_for_department: "Acting",
      name: "Edward Teller",
      original_name: "Edward Teller",
      popularity: 2.708,
      profile_path: "/620VHpSWATn3ndeYQd6PHtOeemY.jpg",
      cast_id: 110,
      character: "Self - Theoretical Physicist (archive footage)",
      credit_id: "64b2edc70e4fc8011e063437",
      order: 21,
    },
    {
      adult: false,
      gender: 1,
      id: 1761883,
      known_for_department: "Acting",
      name: "Eleanor Roosevelt",
      original_name: "Eleanor Roosevelt",
      popularity: 3.572,
      profile_path: "/e0CrFliRPVApwLYdvSwZNrL4xyD.jpg",
      cast_id: 111,
      character: "Self (archive footage)",
      credit_id: "64b2edf5e0ca7f00c8ce3956",
      order: 22,
    },
    {
      adult: false,
      gender: 1,
      id: 1220593,
      known_for_department: "Acting",
      name: "Judy Woodruff",
      original_name: "Judy Woodruff",
      popularity: 2.727,
      profile_path: "/vzCVswqYMTAEGuRMZp6CQdmqInG.jpg",
      cast_id: 112,
      character: "Self (voice) (archive footage)",
      credit_id: "64b2ee5437806200e2aaf027",
      order: 23,
    },
    {
      adult: false,
      gender: 2,
      id: 10279,
      known_for_department: "Acting",
      name: "Adolf Hitler",
      original_name: "Adolf Hitler",
      popularity: 11.584,
      profile_path: "/n6f81IUSes1a8jTzUIF7rJ5zZnP.jpg",
      cast_id: 96,
      character: "Self (archive footage)",
      credit_id: "64b2e92d78570e013a9156e6",
      order: 24,
    },
    {
      adult: false,
      gender: 2,
      id: 1004584,
      known_for_department: "Acting",
      name: "Vladimir Putin",
      original_name: "Vladimir Putin",
      popularity: 7.05,
      profile_path: "/2KAiDj7MtlhXWmdELym9wQuRJCa.jpg",
      cast_id: 113,
      character: "Self (archive Footage)",
      credit_id: "64d026486d4c97014f42af12",
      order: 25,
    },
    {
      adult: false,
      gender: 2,
      id: 2342141,
      known_for_department: "Acting",
      name: "Xi Jinping",
      original_name: "Xi Jinping",
      popularity: 3.575,
      profile_path: "/kw0UwTQtDBdKKGUoHvRaWEvmX8T.jpg",
      cast_id: 114,
      character: "Self (archive Footage)",
      credit_id: "64d0268c945d3600c572fe6e",
      order: 26,
    },
    {
      adult: false,
      gender: 2,
      id: 1317625,
      known_for_department: "Acting",
      name: "Albert Einstein",
      original_name: "Albert Einstein",
      popularity: 3.153,
      profile_path: "/d6jZbDseFCdkQhLbKck8RjqPMck.jpg",
      cast_id: 115,
      character: "Self (archive Footage)",
      credit_id: "64d026986d4c9700cb7e5690",
      order: 27,
    },
  ],
  crew: [
    {
      adult: false,
      gender: 2,
      id: 525,
      known_for_department: "Directing",
      name: "Christopher Nolan",
      original_name: "Christopher Nolan",
      popularity: 34.607,
      profile_path: "/xuAIuYSmsUzKlUMBFGVZaWsY3DZ.jpg",
      credit_id: "64b2e5a40e4fc8011e0631c4",
      department: "Crew",
      job: "Thanks",
    },
    {
      adult: false,
      gender: 1,
      id: 556,
      known_for_department: "Production",
      name: "Emma Thomas",
      original_name: "Emma Thomas",
      popularity: 17.139,
      profile_path: "/6GemtNCy856iLho6WRsFASxQTAp.jpg",
      credit_id: "64b2e5a8e0ca7f00ae756a1d",
      department: "Crew",
      job: "Thanks",
    },
    {
      adult: false,
      gender: 0,
      id: 88553,
      known_for_department: "Production",
      name: "Zeke Dunn",
      original_name: "Zeke Dunn",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e41b23d278014584a6ff",
      department: "Production",
      job: "Line Producer",
    },
    {
      adult: false,
      gender: 2,
      id: 225369,
      known_for_department: "Directing",
      name: "Christopher Cassel",
      original_name: "Christopher Cassel",
      popularity: 1.4,
      profile_path: null,
      credit_id: "64aaeb7ce24b930100c6461d",
      department: "Directing",
      job: "Director",
    },
    {
      adult: false,
      gender: 2,
      id: 225369,
      known_for_department: "Directing",
      name: "Christopher Cassel",
      original_name: "Christopher Cassel",
      popularity: 1.4,
      profile_path: null,
      credit_id: "64b2e30237806200e2aaec49",
      department: "Production",
      job: "Executive Producer",
    },
    {
      adult: false,
      gender: 2,
      id: 1205130,
      known_for_department: "Art",
      name: "Caley Bisson",
      original_name: "Caley Bisson",
      popularity: 0.608,
      profile_path: null,
      credit_id: "64b2e55378570e010088def6",
      department: "Art",
      job: "Production Design",
    },
    {
      adult: false,
      gender: 1,
      id: 1244039,
      known_for_department: "Production",
      name: "Molly O'Brien",
      original_name: "Molly O'Brien",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e2a4e0ca7f00c8ce35ac",
      department: "Production",
      job: "Executive Producer",
    },
    {
      adult: false,
      gender: 2,
      id: 1284276,
      known_for_department: "Sound",
      name: "Adriano Bravo",
      original_name: "Adriano Bravo",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e574378062011c8b04aa",
      department: "Sound",
      job: "Sound Mixer",
    },
    {
      adult: false,
      gender: 0,
      id: 1460656,
      known_for_department: "Camera",
      name: "Brandon Taylor",
      original_name: "Brandon Taylor",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e509c8a2d4011d76654d",
      department: "Camera",
      job: "Grip",
    },
    {
      adult: false,
      gender: 1,
      id: 1570638,
      known_for_department: "Art",
      name: "Sarah Loeppke",
      original_name: "Sarah Loeppke",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e5580bb076012d57f82f",
      department: "Art",
      job: "Production Design",
    },
    {
      adult: false,
      gender: 1,
      id: 1578345,
      known_for_department: "Production",
      name: "Liz Cole",
      original_name: "Liz Cole",
      popularity: 0.98,
      profile_path: null,
      credit_id: "64b2e1cdc8a2d4011d766444",
      department: "Production",
      job: "Executive Producer",
    },
    {
      adult: false,
      gender: 0,
      id: 1670921,
      known_for_department: "Camera",
      name: "Brandon Ripley",
      original_name: "Brandon Ripley",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e42e37806200e2aaecbe",
      department: "Camera",
      job: "Additional Director of Photography",
    },
    {
      adult: false,
      gender: 0,
      id: 1677946,
      known_for_department: "Crew",
      name: "Ben Carolan",
      original_name: "Ben Carolan",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e45078570e00ad4b5aef",
      department: "Camera",
      job: "First Assistant Camera",
    },
    {
      adult: false,
      gender: 0,
      id: 1768734,
      known_for_department: "Editing",
      name: "Jake Vest",
      original_name: "Jake Vest",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e6a5c8a2d4011d7665e3",
      department: "Production",
      job: "Post Production Coordinator",
    },
    {
      adult: false,
      gender: 2,
      id: 1787583,
      known_for_department: "Camera",
      name: "Tim Metzger",
      original_name: "Tim Metzger",
      popularity: 1.4,
      profile_path: null,
      credit_id: "64b2e312e0ca7f014429d978",
      department: "Camera",
      job: "Director of Photography",
    },
    {
      adult: false,
      gender: 1,
      id: 1834743,
      known_for_department: "Production",
      name: "Elizabeth Fischer",
      original_name: "Elizabeth Fischer",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e2fee0ca7f01253d02e8",
      department: "Production",
      job: "Executive Producer",
    },
    {
      adult: false,
      gender: 0,
      id: 1882148,
      known_for_department: "Visual Effects",
      name: "Ben Kiviat",
      original_name: "Ben Kiviat",
      popularity: 0.98,
      profile_path: null,
      credit_id: "64b2e70c37806200ad1472b4",
      department: "Editing",
      job: "Digital Intermediate Editor",
    },
    {
      adult: false,
      gender: 1,
      id: 1931189,
      known_for_department: "Editing",
      name: "Rosie Walunas",
      original_name: "Rosie Walunas",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e32f0e4fc8011e0630d1",
      department: "Editing",
      job: "Editor",
    },
    {
      adult: false,
      gender: 1,
      id: 2005644,
      known_for_department: "Sound",
      name: "Anna Drubich",
      original_name: "Anna Drubich",
      popularity: 3.057,
      profile_path: null,
      credit_id: "64b2e3490bb076014e4ea5f9",
      department: "Sound",
      job: "Original Music Composer",
    },
    {
      adult: false,
      gender: 2,
      id: 2140527,
      known_for_department: "Production",
      name: "Thaddeus Bouska",
      original_name: "Thaddeus Bouska",
      popularity: 0.98,
      profile_path: null,
      credit_id: "64b2e3b63780620139068e00",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      gender: 2,
      id: 2183092,
      known_for_department: "Sound",
      name: "David Thompson",
      original_name: "David Thompson",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e56cc8a2d400e3933b05",
      department: "Sound",
      job: "Sound Mixer",
    },
    {
      adult: false,
      gender: 0,
      id: 2296709,
      known_for_department: "Camera",
      name: "Henry Sime",
      original_name: "Henry Sime",
      popularity: 1.38,
      profile_path: null,
      credit_id: "64b2e4ffe0ca7f00ae7569d5",
      department: "Camera",
      job: "Grip",
    },
    {
      adult: false,
      gender: 2,
      id: 2378258,
      known_for_department: "Production",
      name: "Joel Schneider",
      original_name: "Joel Schneider",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e3b178570e00e33ad4e7",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      gender: 0,
      id: 2537044,
      known_for_department: "Camera",
      name: "Meghan Noce",
      original_name: "Meghan Noce",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e462e0ca7f0106975344",
      department: "Camera",
      job: "First Assistant Camera",
    },
    {
      adult: false,
      gender: 0,
      id: 2648623,
      known_for_department: "Lighting",
      name: "Isaak van der Meulen",
      original_name: "Isaak van der Meulen",
      popularity: 0.98,
      profile_path: null,
      credit_id: "64b2e4c123d27800e88b0f89",
      department: "Lighting",
      job: "Gaffer",
    },
    {
      adult: false,
      gender: 2,
      id: 2676962,
      known_for_department: "Sound",
      name: "Dan Walsh",
      original_name: "Dan Walsh",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e72a78570e013a915637",
      department: "Sound",
      job: "Supervising Sound Editor",
    },
    {
      adult: false,
      gender: 2,
      id: 2676962,
      known_for_department: "Sound",
      name: "Dan Walsh",
      original_name: "Dan Walsh",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e7330bb076012d57f8f7",
      department: "Sound",
      job: "Sound Re-Recording Mixer",
    },
    {
      adult: false,
      gender: 0,
      id: 2736252,
      known_for_department: "Camera",
      name: "Andrew Goh",
      original_name: "Andrew Goh",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e45f37806200e2aaeccd",
      department: "Camera",
      job: "First Assistant Camera",
    },
    {
      adult: false,
      gender: 0,
      id: 2819065,
      known_for_department: "Camera",
      name: "George Alvarez",
      original_name: "George Alvarez",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e439c8a2d401001e719a",
      department: "Camera",
      job: "First Assistant Camera",
    },
    {
      adult: false,
      gender: 2,
      id: 2848340,
      known_for_department: "Acting",
      name: "Michael Oppenheimer",
      original_name: "Michael Oppenheimer",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e5b223d27801261a12d9",
      department: "Crew",
      job: "Thanks",
    },
    {
      adult: false,
      gender: 1,
      id: 2953688,
      known_for_department: "Camera",
      name: "Colleen Newberry",
      original_name: "Colleen Newberry",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e4ebe0ca7f014429da29",
      department: "Camera",
      job: "Grip",
    },
    {
      adult: false,
      gender: 0,
      id: 2978064,
      known_for_department: "Lighting",
      name: "Joe Kosty",
      original_name: "Joe Kosty",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e5403780620139068ec6",
      department: "Art",
      job: "Swing",
    },
    {
      adult: false,
      gender: 0,
      id: 3016092,
      known_for_department: "Editing",
      name: "Anthony Campagna",
      original_name: "Anthony Campagna",
      popularity: 0.98,
      profile_path: null,
      credit_id: "64b2e6fc78570e010088dfa2",
      department: "Editing",
      job: "Digital Intermediate Colorist",
    },
    {
      adult: false,
      gender: 0,
      id: 3190272,
      known_for_department: "Camera",
      name: "Phillip Yu",
      original_name: "Phillip Yu",
      popularity: 0.98,
      profile_path: null,
      credit_id: "64b2e4d5c8a2d4011d766536",
      department: "Lighting",
      job: "Gaffer",
    },
    {
      adult: false,
      gender: 0,
      id: 3190272,
      known_for_department: "Camera",
      name: "Phillip Yu",
      original_name: "Phillip Yu",
      popularity: 0.98,
      profile_path: null,
      credit_id: "64b2e5210bb07600ae3bbce4",
      department: "Camera",
      job: "Grip",
    },
    {
      adult: false,
      gender: 0,
      id: 3241177,
      known_for_department: "Lighting",
      name: "Ryan Halsey",
      original_name: "Ryan Halsey",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e49678570e00e33ad526",
      department: "Lighting",
      job: "Gaffer",
    },
    {
      adult: false,
      gender: 0,
      id: 3366261,
      known_for_department: "Camera",
      name: "Xavier Gomez",
      original_name: "Xavier Gomez",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e4a20e4fc800e3351ca5",
      department: "Lighting",
      job: "Gaffer",
    },
    {
      adult: false,
      gender: 0,
      id: 3405908,
      known_for_department: "Camera",
      name: "Coburn Erskine",
      original_name: "Coburn Erskine",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e45ac8a2d4013af6ecf2",
      department: "Camera",
      job: "First Assistant Camera",
    },
    {
      adult: false,
      gender: 0,
      id: 3512528,
      known_for_department: "Camera",
      name: "Joshua Jones",
      original_name: "Joshua Jones",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e46fe0ca7f00e771ad1b",
      department: "Camera",
      job: "Second Assistant Camera",
    },
    {
      adult: false,
      gender: 2,
      id: 3552335,
      known_for_department: "Sound",
      name: "Dave Richards",
      original_name: "Dave Richards",
      popularity: 0.98,
      profile_path: null,
      credit_id: "64b2e57fe0ca7f00c8ce36a6",
      department: "Sound",
      job: "Sound Mixer",
    },
    {
      adult: false,
      gender: 1,
      id: 3874336,
      known_for_department: "Production",
      name: "Eleanor West",
      original_name: "Eleanor West",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e3fe0e4fc8011e06310f",
      department: "Production",
      job: "Co-Producer",
    },
    {
      adult: false,
      gender: 2,
      id: 3966522,
      known_for_department: "Editing",
      name: "Barry Blaschke",
      original_name: "Barry Blaschke",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e32b23d2780107306f6e",
      department: "Editing",
      job: "Editor",
    },
    {
      adult: false,
      gender: 0,
      id: 4005799,
      known_for_department: "Camera",
      name: "Aaron Johnson",
      original_name: "Aaron Johnson",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e4dc37806200e2aaed0d",
      department: "Camera",
      job: "Grip",
    },
    {
      adult: false,
      gender: 1,
      id: 4164355,
      known_for_department: "Production",
      name: "Laura Juncadella",
      original_name: "Laura Juncadella",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e404c8a2d400c622a0e3",
      department: "Production",
      job: "Associate Producer",
    },
    {
      adult: false,
      gender: 0,
      id: 4164356,
      known_for_department: "Production",
      name: "Kira Leinonen",
      original_name: "Kira Leinonen",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e40b0bb076014e4ea64d",
      department: "Production",
      job: "Line Producer",
    },
    {
      adult: false,
      gender: 0,
      id: 4164357,
      known_for_department: "Production",
      name: "Micky Haney",
      original_name: "Micky Haney",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e41023d27800adc8badb",
      department: "Production",
      job: "Production Manager",
    },
    {
      adult: false,
      gender: 0,
      id: 4164358,
      known_for_department: "Production",
      name: "Marisa Reilly",
      original_name: "Marisa Reilly",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e4150e4fc80101825fe3",
      department: "Production",
      job: "Head of Production",
    },
    {
      adult: false,
      gender: 0,
      id: 4164360,
      known_for_department: "Production",
      name: "Amanda Moore",
      original_name: "Amanda Moore",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e4250e4fc800e3351c79",
      department: "Production",
      job: "Production Manager",
    },
    {
      adult: false,
      gender: 0,
      id: 4164362,
      known_for_department: "Camera",
      name: "Will Dauel",
      original_name: "Will Dauel",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e45537806200c586e780",
      department: "Camera",
      job: "First Assistant Camera",
    },
    {
      adult: false,
      gender: 0,
      id: 4164363,
      known_for_department: "Camera",
      name: "Nick Misisco",
      original_name: "Nick Misisco",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e478e0ca7f00ae756993",
      department: "Camera",
      job: "Second Assistant Camera",
    },
    {
      adult: false,
      gender: 0,
      id: 4164364,
      known_for_department: "Camera",
      name: "Donovon O'Neill",
      original_name: "Donovon O'Neill",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e48637806200e2aaecee",
      department: "Camera",
      job: "Second Assistant Camera",
    },
    {
      adult: false,
      gender: 0,
      id: 4164365,
      known_for_department: "Camera",
      name: "Oleksandr Shvachko",
      original_name: "Oleksandr Shvachko",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e48c37806200ad1471ae",
      department: "Camera",
      job: "Second Assistant Camera",
    },
    {
      adult: false,
      gender: 0,
      id: 4164366,
      known_for_department: "Camera",
      name: "Madison Stonefield",
      original_name: "Madison Stonefield",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e49278570e010088dea0",
      department: "Camera",
      job: "Second Assistant Camera",
    },
    {
      adult: false,
      gender: 0,
      id: 4164367,
      known_for_department: "Lighting",
      name: "Curt Jentsch",
      original_name: "Curt Jentsch",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e49b3780620139068e7a",
      department: "Lighting",
      job: "Gaffer",
    },
    {
      adult: false,
      gender: 0,
      id: 4164370,
      known_for_department: "Lighting",
      name: "Greg Smith",
      original_name: "Greg Smith",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e4bbc8a2d401001e71d6",
      department: "Lighting",
      job: "Gaffer",
    },
    {
      adult: false,
      gender: 0,
      id: 4164371,
      known_for_department: "Lighting",
      name: "Michael Wilson",
      original_name: "Michael Wilson",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e4d00bb076010c50cc37",
      department: "Lighting",
      job: "Gaffer",
    },
    {
      adult: false,
      gender: 0,
      id: 4164373,
      known_for_department: "Camera",
      name: 'Jose "FX" Rodriquez',
      original_name: 'Jose "FX" Rodriquez',
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e4fb378062011c8b0479",
      department: "Camera",
      job: "Grip",
    },
    {
      adult: false,
      gender: 0,
      id: 4164374,
      known_for_department: "Camera",
      name: "James Wilson",
      original_name: "James Wilson",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e51ce0ca7f010697539a",
      department: "Camera",
      job: "Grip",
    },
    {
      adult: false,
      gender: 0,
      id: 4164375,
      known_for_department: "Art",
      name: "Christopher Burke",
      original_name: "Christopher Burke",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e52be0ca7f00ae7569ee",
      department: "Art",
      job: "Swing",
    },
    {
      adult: false,
      gender: 0,
      id: 4164376,
      known_for_department: "Art",
      name: "Dylan Henderson",
      original_name: "Dylan Henderson",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e52f0e4fc8013b544c0a",
      department: "Art",
      job: "Swing",
    },
    {
      adult: false,
      gender: 0,
      id: 4164377,
      known_for_department: "Art",
      name: "David Hsu",
      original_name: "David Hsu",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e53c0e4fc800c683766c",
      department: "Art",
      job: "Swing",
    },
    {
      adult: false,
      gender: 0,
      id: 4164378,
      known_for_department: "Art",
      name: "David Persaud",
      original_name: "David Persaud",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e54b37806200c586e7f5",
      department: "Art",
      job: "Swing",
    },
    {
      adult: false,
      gender: 1,
      id: 4164380,
      known_for_department: "Art",
      name: "Anna Kendall",
      original_name: "Anna Kendall",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e5620bb076012d57f83f",
      department: "Art",
      job: "Set Dresser",
    },
    {
      adult: false,
      gender: 0,
      id: 4164381,
      known_for_department: "Sound",
      name: "Stu Chacon",
      original_name: "Stu Chacon",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e5790bb07600ae3bbd0e",
      department: "Sound",
      job: "Sound Mixer",
    },
    {
      adult: false,
      gender: 0,
      id: 4164382,
      known_for_department: "Sound",
      name: "Wally Skinner",
      original_name: "Wally Skinner",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e58337806200e2aaed5a",
      department: "Sound",
      job: "Sound Mixer",
    },
    {
      adult: false,
      gender: 0,
      id: 4164383,
      known_for_department: "Sound",
      name: "Tony Smith",
      original_name: "Tony Smith",
      popularity: 0.98,
      profile_path: null,
      credit_id: "64b2e58de0ca7f00ae756a12",
      department: "Sound",
      job: "Sound Mixer",
    },
    {
      adult: false,
      gender: 0,
      id: 4164384,
      known_for_department: "Crew",
      name: "Emma Belcher",
      original_name: "Emma Belcher",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e5ac23d278014584a7be",
      department: "Crew",
      job: "Thanks",
    },
    {
      adult: false,
      gender: 0,
      id: 4164388,
      known_for_department: "Crew",
      name: "Dr. Jorge López",
      original_name: "Dr. Jorge López",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e65a78570e00ad4b5bba",
      department: "Crew",
      job: "Thanks",
    },
    {
      adult: false,
      gender: 1,
      id: 4164389,
      known_for_department: "Acting",
      name: "Hideko Tamura",
      original_name: "Hideko Tamura",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e66123d27800c93bc35e",
      department: "Crew",
      job: "Thanks",
    },
    {
      adult: false,
      gender: 0,
      id: 4164390,
      known_for_department: "Crew",
      name: "Noriko Hansen",
      original_name: "Noriko Hansen",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e66678570e00e33ad5cb",
      department: "Crew",
      job: "Thanks",
    },
    {
      adult: false,
      gender: 0,
      id: 4164391,
      known_for_department: "Crew",
      name: 'John "Drew" Hamilton',
      original_name: 'John "Drew" Hamilton',
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e6720e4fc800c68376f4",
      department: "Crew",
      job: "Thanks",
    },
    {
      adult: false,
      gender: 0,
      id: 4164392,
      known_for_department: "Crew",
      name: "Alex Pilkington",
      original_name: "Alex Pilkington",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e69c0bb07600eb28ccdb",
      department: "Crew",
      job: "Post Production Supervisor",
    },
    {
      adult: false,
      gender: 1,
      id: 4164393,
      known_for_department: "Editing",
      name: "Sophia Oliveri",
      original_name: "Sophia Oliveri",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e6abc8a2d400e3933b6c",
      department: "Editing",
      job: "Assistant Editor",
    },
    {
      adult: false,
      gender: 0,
      id: 4164395,
      known_for_department: "Visual Effects",
      name: "Mike Sweeney",
      original_name: "Mike Sweeney",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e6d3378062011c8b054e",
      department: "Visual Effects",
      job: "Animation",
    },
    {
      adult: false,
      gender: 0,
      id: 4164395,
      known_for_department: "Visual Effects",
      name: "Mike Sweeney",
      original_name: "Mike Sweeney",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e6bf0bb07600ae3bbd9c",
      department: "Visual Effects",
      job: "Animation Director",
    },
    {
      adult: false,
      gender: 2,
      id: 4164396,
      known_for_department: "Art",
      name: "Jonathan Hunt",
      original_name: "Jonathan Hunt",
      popularity: 0.98,
      profile_path: null,
      credit_id: "64b2e6c678570e013a915605",
      department: "Art",
      job: "Art Direction",
    },
    {
      adult: false,
      gender: 2,
      id: 4164396,
      known_for_department: "Art",
      name: "Jonathan Hunt",
      original_name: "Jonathan Hunt",
      popularity: 0.98,
      profile_path: null,
      credit_id: "64b2e6db0bb076010c50ccf1",
      department: "Visual Effects",
      job: "Animation",
    },
    {
      adult: false,
      gender: 2,
      id: 4164397,
      known_for_department: "Art",
      name: "Jeff Gess",
      original_name: "Jeff Gess",
      popularity: 0.98,
      profile_path: null,
      credit_id: "64b2e6ccc8a2d401001e7283",
      department: "Art",
      job: "Art Direction",
    },
    {
      adult: false,
      gender: 2,
      id: 4164397,
      known_for_department: "Art",
      name: "Jeff Gess",
      original_name: "Jeff Gess",
      popularity: 0.98,
      profile_path: null,
      credit_id: "64b2e6d623d27801073070f7",
      department: "Visual Effects",
      job: "Animation",
    },
    {
      adult: false,
      gender: 0,
      id: 4164399,
      known_for_department: "Visual Effects",
      name: "Shane Douberly",
      original_name: "Shane Douberly",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e6e00bb076014e4ea756",
      department: "Visual Effects",
      job: "Animation",
    },
    {
      adult: false,
      gender: 0,
      id: 4164401,
      known_for_department: "Production",
      name: "Katie Janse",
      original_name: "Katie Janse",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e6e80bb076012d57f8d7",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      gender: 0,
      id: 4164406,
      known_for_department: "Sound",
      name: "Joe DiCosola",
      original_name: "Joe DiCosola",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e7413780620139068f98",
      department: "Sound",
      job: "Sound Effects Editor",
    },
    {
      adult: false,
      gender: 0,
      id: 4164407,
      known_for_department: "Production",
      name: "Tanner DeMain",
      original_name: "Tanner DeMain",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e749e0ca7f014429db18",
      department: "Production",
      job: "Production Assistant",
    },
    {
      adult: false,
      gender: 0,
      id: 4164408,
      known_for_department: "Production",
      name: "DeDric Hohman",
      original_name: "DeDric Hohman",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e750e0ca7f0106975481",
      department: "Production",
      job: "Production Assistant",
    },
    {
      adult: false,
      gender: 0,
      id: 4164409,
      known_for_department: "Production",
      name: "Mikey Slavich",
      original_name: "Mikey Slavich",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e7550bb07600caf8788d",
      department: "Production",
      job: "Production Assistant",
    },
    {
      adult: false,
      gender: 0,
      id: 4164410,
      known_for_department: "Production",
      name: "Edgar Polkat",
      original_name: "Edgar Polkat",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e7590bb07600ae3bbdda",
      department: "Production",
      job: "Production Assistant",
    },
    {
      adult: false,
      gender: 0,
      id: 4164411,
      known_for_department: "Production",
      name: "Sam Worrin",
      original_name: "Sam Worrin",
      popularity: 0.6,
      profile_path: null,
      credit_id: "64b2e75dc8a2d4013af6edfc",
      department: "Production",
      job: "Production Assistant",
    },
  ],
} as Object as Credits;

export { dummyResults, dummyCredits };
