import { Movie } from "./schemas/movie";

// Data from https://www.themoviedb.org/

const dummyResults: Movie[] = [
  {
    adult: false,
    backdrop_path: "/iUAFLqAj7p1v8zkOReyd7tjSLDg.jpg",
    genre_ids: [18, 35],
    id: 341744,
    original_language: "es",
    original_title: "Truman",
    overview:
      "Tomás, who lives in Canada, travels to Madrid, Spain, to visit his old friend Julián. Both of them, accompanied by Truman, Julián's faithful dog, will share many surprising and emotional little moments, triggered by the hard situation Julián is going through, for just a few days.",
    popularity: 9.364,
    poster_path: "/p4MFl06ePJGKMIF7zFCJhex95Vi.jpg",
    release_date: "2015-09-24",
    title: "Truman",
    video: false,
    vote_average: 7.006,
    vote_count: 346,
  },
  {
    adult: false,
    backdrop_path: "/xZRuns3IlPxnzpHhbscAOLyiwNr.jpg",
    genre_ids: [18, 10770],
    id: 16901,
    original_language: "en",
    original_title: "Truman",
    overview:
      "Biographical account of America's President for the latter part of WWII. Shows Truman's rise from small-town nobody to leader of the USA, his decision to use the Atomic Bomb against Japan, and subsequent election as the US' post-war President.",
    popularity: 2.905,
    poster_path: "/4SW6da4XjxLGlRVS079O1ORpjqk.jpg",
    release_date: "1995-09-09",
    title: "Truman",
    video: false,
    vote_average: 7.6,
    vote_count: 15,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [99],
    id: 365256,
    original_language: "en",
    original_title: "Truman",
    overview:
      "He was a farmer, a businessman, an unknown politician who suddenly found himself president. Of all the men who had held the highest office, Harry Truman was the least prepared, but would prove to be a surprise.",
    popularity: 0.6,
    poster_path: null,
    release_date: "1997-10-05",
    title: "Truman",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/aCHn2TXYJfzPXQKA6r9mKPbMlUB.jpg",
    genre_ids: [35, 18],
    id: 37165,
    original_language: "en",
    original_title: "The Truman Show",
    overview:
      "Truman Burbank is the star of The Truman Show, a 24-hour-a-day reality TV show that broadcasts every aspect of his life without his knowledge. His entire life has been an unending soap opera for consumption by the rest of the world. And everyone he knows, including his wife and his best friend, is really an actor, paid to be part of his life.",
    popularity: 71.661,
    poster_path: "/vuza0WqY239yBXOadKlGwJsZJFE.jpg",
    release_date: "1998-06-04",
    title: "The Truman Show",
    video: false,
    vote_average: 8.132,
    vote_count: 16690,
  },
  {
    adult: false,
    backdrop_path: "/pmsfi7seRvhj5FpR1T1USD08txG.jpg",
    genre_ids: [99],
    id: 730081,
    original_language: "en",
    original_title: "Truman & Tennessee: An Intimate Conversation",
    overview:
      "The parallel lives of writer Truman Capote (1924-84) and playwright Tennessee Williams (1911-83): two friends, two geniuses who, while creating sublime works, were haunted by the ghosts of the past, the shadow of constant doubt, the demon of addictions and the blinding, deceptive glare of success.",
    popularity: 2.632,
    poster_path: "/yBLui5HtiyAFWQqVXjqSdJeRLdv.jpg",
    release_date: "2021-06-18",
    title: "Truman & Tennessee: An Intimate Conversation",
    video: false,
    vote_average: 4,
    vote_count: 2,
  },
  {
    adult: false,
    backdrop_path: "/zYTNycZ3QPGFwlUbRrjyPkWvik4.jpg",
    genre_ids: [99],
    id: 298662,
    original_language: "en",
    original_title: "With Love from Truman",
    overview:
      "At his Long Island beach house, and on the occasion of the publication of his masterful nonfiction novel In Cold Blood, reporter Karen Dennison interviews celebrated writer Truman Capote, who displays his exuberant personality, makes witty jokes, shares his thoughts on writing, reflects on various aspects of the book and, in a sweet and endearing voice, reads and explains some of its highlights.",
    popularity: 0.812,
    poster_path: "/n60IVg19EaNNRwqvpGatOGlsWIY.jpg",
    release_date: "1966-01-01",
    title: "With Love from Truman",
    video: false,
    vote_average: 6.2,
    vote_count: 6,
  },
  {
    adult: false,
    backdrop_path: "/pUH4DkA9THIrCXhKp5UFLhjLDyh.jpg",
    genre_ids: [99],
    id: 742930,
    original_language: "en",
    original_title: "How's It Going to End - The Making of 'The Truman Show'",
    overview: "The making of 'The Truman Show'.",
    popularity: 0.676,
    poster_path: "/3u7lkckEG1KJK1yWnBL0FMVg9qg.jpg",
    release_date: "2005-08-19",
    title: "How's It Going to End - The Making of 'The Truman Show'",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [18, 10770],
    id: 263221,
    original_language: "en",
    original_title: "Harry S. Truman: Plain Speaking",
    overview: "A biography of President Harry S. Truman.",
    popularity: 0.654,
    poster_path: "/7EzzuZQEHqjOwMoV1T4J37VqPkg.jpg",
    release_date: "1976-10-06",
    title: "Harry S. Truman: Plain Speaking",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/32YCKPHxiMZcH2MOzSBZsF0EEk6.jpg",
    genre_ids: [10402],
    id: 1067909,
    original_language: "en",
    original_title: "Goose: 2021.11.17 - The Truman - Kansas City, MO",
    overview:
      "Set 1: Earthlings or Alien? > Indian River > Doctor My Eyes, SOS, All I Need > Bob Don > All I Need  Set 2: Arcadia > Crosseyed and Painless > Drive > Moby, 726, Into The Myst  Encore: Doobie Song",
    popularity: 0.6,
    poster_path: "/f4fbK3qI4UyFIZVXlXfkCrqtiYd.jpg",
    release_date: "2021-11-17",
    title: "Goose: 2021.11.17 - The Truman - Kansas City, MO",
    video: true,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/xLANFjyrdj0qUeQUkaFUDkXgrJ.jpg",
    genre_ids: [99, 10752, 36],
    id: 594957,
    original_language: "fr",
    original_title: "Staline-Truman, l'aube de la guerre froide",
    overview: "",
    popularity: 0.6,
    poster_path: "/nSgkcYxPTVucOXdsjfCjxTWytKn.jpg",
    release_date: "2019-04-04",
    title: "Staline-Truman, l'aube de la guerre froide",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [99],
    id: 670673,
    original_language: "de",
    original_title:
      "Truman Capote - Enfant terrible der amerikanischen Literatur",
    overview: "",
    popularity: 0.63,
    poster_path: "/1zS7gZUetZdojLEA3kwJOZThbQr.jpg",
    release_date: "2016-11-16",
    title: "Truman Capote - Enfant terrible der amerikanischen Literatur",
    video: false,
    vote_average: 9,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [99],
    id: 973055,
    original_language: "en",
    original_title: "Truman Capote: Answered Prayers",
    overview:
      "A short documentary looking at how the film Capote was developed, the motivations of those involved, and insights from Gerald Clarke, Capote's friend and biographer.",
    popularity: 0.6,
    poster_path: "/qNcdLvqoG3i37ceDyy3WjmEc7lR.jpg",
    release_date: "2006-03-21",
    title: "Truman Capote: Answered Prayers",
    video: false,
    vote_average: 4,
    vote_count: 2,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [18],
    id: 786749,
    original_language: "en",
    original_title: "Truman Syndrome",
    overview:
      "A person who believes they're being watched all day, every day, struggles with their mental health and their grip on reality.",
    popularity: 0.6,
    poster_path: "/f3lrhJr7M8pk1A0ljUzrnUgsjCP.jpg",
    release_date: "2021-01-21",
    title: "Truman Syndrome",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 810559,
    original_language: "en",
    original_title: "David Susskind Archive: Truman Capote Tells All",
    overview:
      "An extensive interview originally broadcast in Feb. 1979. Host David Susskind and Truman Capote discuss the icon's history, his writing, his social persona and impact. More than an interview, the wide-ranging conversation between longtime friends delves into topics you are unlikely to see elsewhere.",
    popularity: 0.6,
    poster_path: null,
    release_date: "",
    title: "David Susskind Archive: Truman Capote Tells All",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [10752, 18, 10770],
    id: 1156740,
    original_language: "en",
    original_title: "Collision Course: Truman vs. MacArthur",
    overview:
      "U.S. President Harry S Truman and his commander in the Korean War, General Douglas MacArthur, disagree on war strategy. Their conflict comes to a head when Truman relieves the insubordinate MacArthur from command.",
    popularity: 0.6,
    poster_path: null,
    release_date: "1976-01-04",
    title: "Collision Course: Truman vs. MacArthur",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/gQYsE1Zu89fbi3yUL4bubxoRjbh.jpg",
    genre_ids: [80, 18],
    id: 18900,
    original_language: "en",
    original_title: "In Cold Blood",
    overview:
      "After a botched robbery results in the brutal murder of a rural family, two drifters elude police, in the end coming to terms with their own mortality and the repercussions of their vile atrocity.",
    popularity: 12.319,
    poster_path: "/9VFk7hyx3Thk8kzChq750rLtrsR.jpg",
    release_date: "1967-12-15",
    title: "In Cold Blood",
    video: false,
    vote_average: 7.5,
    vote_count: 313,
  },
  {
    adult: false,
    backdrop_path: "/kA28hzGAais4Rlk0RG6PsQzTqU4.jpg",
    genre_ids: [18, 80],
    id: 9672,
    original_language: "en",
    original_title: "Infamous",
    overview:
      "While researching his book In Cold Blood, writer Truman Capote develops a close relationship with convicted murderers Dick Hickock and Perry Smith.",
    popularity: 11.293,
    poster_path: "/cIQUn20lUQpi70W0Z7ixezQJ7gj.jpg",
    release_date: "2006-09-11",
    title: "Infamous",
    video: false,
    vote_average: 6.478,
    vote_count: 179,
  },
  {
    adult: false,
    backdrop_path: "/gBn3af5QvQARNZEFlvYjFO268I7.jpg",
    genre_ids: [80, 18],
    id: 398,
    original_language: "en",
    original_title: "Capote",
    overview:
      'A biopic of writer Truman Capote and his assignment for The New Yorker to write the non-fiction book "In Cold Blood".',
    popularity: 12.676,
    poster_path: "/k7z0tDxzbDNev7F8l3Y56Pk5seR.jpg",
    release_date: "2005-09-30",
    title: "Capote",
    video: false,
    vote_average: 6.998,
    vote_count: 1287,
  },
  {
    adult: false,
    backdrop_path: "/r3eo0srAqazG1lFMuqPzJqdyGce.jpg",
    genre_ids: [99],
    id: 621769,
    original_language: "en",
    original_title: "The Capote Tapes",
    overview:
      "Newly discovered interviews with friends of Truman Capote made by Paris Review co-founder George Plimpton invigorate this fascinating documentary on the author (and socialite) behind Breakfast at Tiffany’s and In Cold Blood, while situating Capote in the 20th-century American literary canon.",
    popularity: 4.311,
    poster_path: "/iOxtoUHHxDF9ZEhTNqFUWjpWgDH.jpg",
    release_date: "2021-09-10",
    title: "The Capote Tapes",
    video: false,
    vote_average: 7.8,
    vote_count: 4,
  },
  {
    adult: false,
    backdrop_path: "/2Fa1IO7qcXX9KlnocFyhPNUxRwb.jpg",
    genre_ids: [18, 10751],
    id: 147135,
    original_language: "en",
    original_title: "One Christmas",
    overview:
      "Based on Truman Capote's bittersweet tale of a young boy's adventures with the father he's never known in New Orleans in the 1930s..",
    popularity: 1.484,
    poster_path: "/uTVZyFVVJ5WVjH1G08UxeKSv9tw.jpg",
    release_date: "1994-12-19",
    title: "One Christmas",
    video: false,
    vote_average: 5.5,
    vote_count: 8,
  },
] as Object as Movie[];

export { dummyResults };
